import { MenuItem, CanteenSettings } from '../src/types';

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // ================= 1. BEVERAGES & HOT DRINKS (டீ & காபி & பால்) =================
  {
    id: 'item-1',
    code: 'TEA-01',
    nameTamil: 'கிளாஸ் (டீ)',
    nameEnglish: 'Glass Tea',
    category: 'Beverages / Hot Drinks',
    price: 12,
    isVeg: true,
    description: 'Hot authentic South Indian spiced milk tea freshly brewed at the canteen counter.',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 3,
    tags: ['Tea', 'Hot', 'Popular']
  },
  {
    id: 'item-2',
    code: 'COF-01',
    nameTamil: 'கிளாஸ் (காபி)',
    nameEnglish: 'Glass Coffee',
    category: 'Beverages / Hot Drinks',
    price: 15,
    isVeg: true,
    description: 'Aromatic Kumbakonam style South Indian filter coffee with frothy hot milk.',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 3,
    tags: ['Coffee', 'Filter Coffee', 'Hot']
  },
  {
    id: 'item-3',
    code: 'HLK-01',
    nameTamil: 'ஹார்லிக்ஸ் பால்',
    nameEnglish: 'Horlicks Milk',
    category: 'Beverages / Hot Drinks',
    price: 20,
    isVeg: true,
    description: 'Nourishing malted hot milk with original Horlicks mix.',
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 4,
    tags: ['Health Drink', 'Hot']
  },
  {
    id: 'item-4',
    code: 'BST-01',
    nameTamil: 'பூஸ்ட் பால்',
    nameEnglish: 'Boost Milk',
    category: 'Beverages / Hot Drinks',
    price: 20,
    isVeg: true,
    description: 'Energy boosting chocolate malt drink mixed with piping hot fresh milk.',
    imageUrl: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 4,
    tags: ['Boost', 'Chocolate', 'Hot']
  },
  {
    id: 'item-5',
    code: 'TEA-P1',
    nameTamil: 'பார்சல் டீ 1/2',
    nameEnglish: 'Parcel Tea 1/2 (Half Measure)',
    category: 'Beverages / Hot Drinks',
    price: 25,
    isVeg: true,
    description: 'Fresh hot tea packed in heat-resistant takeaway container (serves 2-3 cups).',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 5,
    tags: ['Takeaway', 'Tea']
  },
  {
    id: 'item-6',
    code: 'COF-P1',
    nameTamil: 'பார்சல் காபி 1/2',
    nameEnglish: 'Parcel Coffee 1/2 (Half Measure)',
    category: 'Beverages / Hot Drinks',
    price: 30,
    isVeg: true,
    description: 'Takeaway flask/pack of fresh filter coffee (serves 2-3 cups).',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 5,
    tags: ['Takeaway', 'Coffee']
  },
  {
    id: 'item-7',
    code: 'TEA-P2',
    nameTamil: 'பார்சல் டீ 1',
    nameEnglish: 'Parcel Tea 1 (Full Measure)',
    category: 'Beverages / Hot Drinks',
    price: 40,
    isVeg: true,
    description: 'Large takeaway pack of freshly brewed tea (serves 4-5 cups).',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 5,
    tags: ['Takeaway', 'Tea']
  },
  {
    id: 'item-8',
    code: 'COF-P2',
    nameTamil: 'பார்சல் காபி 1',
    nameEnglish: 'Parcel Coffee 1 (Full Measure)',
    category: 'Beverages / Hot Drinks',
    price: 50,
    isVeg: true,
    description: 'Large takeaway pack of strong filter coffee (serves 4-5 cups).',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 5,
    tags: ['Takeaway', 'Coffee']
  },
  {
    id: 'item-52',
    code: 'VTC-01',
    nameTamil: 'வட்டகப் காபி',
    nameEnglish: 'Vatta Cup Coffee (Brass Dabara/Wide Cup)',
    category: 'Beverages / Hot Drinks',
    price: 25,
    isVeg: true,
    description: 'Traditional wide cup hot filter coffee with rich decoction and frothy top.',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 4,
    tags: ['Special', 'Coffee']
  },
  {
    id: 'item-53',
    code: 'VTT-01',
    nameTamil: 'வட்டகப் டீ',
    nameEnglish: 'Vatta Cup Tea (Wide Cup)',
    category: 'Beverages / Hot Drinks',
    price: 20,
    isVeg: true,
    description: 'Piping hot masala chai served in traditional wide cup.',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 4,
    tags: ['Special', 'Tea']
  },
  {
    id: 'item-54',
    code: 'VTM-01',
    nameTamil: 'வட்டகப் பால்',
    nameEnglish: 'Vatta Cup Milk',
    category: 'Beverages / Hot Drinks',
    price: 20,
    isVeg: true,
    description: 'Warm, sweetened fresh farm milk served in wide cup.',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 3,
    tags: ['Milk']
  },
  {
    id: 'item-55',
    code: 'MLK-01',
    nameTamil: 'பால்',
    nameEnglish: 'Hot Milk',
    category: 'Beverages / Hot Drinks',
    price: 15,
    isVeg: true,
    description: 'Pure hot boiled milk with light sugar.',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 3,
    tags: ['Milk', 'Healthy']
  },
  {
    id: 'item-56',
    code: 'NS-TEA',
    nameTamil: 'நாட்டுசர்க்கரை டீ',
    nameEnglish: 'Nattu Sarkarai Tea (Country Brown Sugar Tea)',
    category: 'Beverages / Hot Drinks',
    price: 15,
    isVeg: true,
    description: 'Healthy tea prepared with organic unrefined cane brown sugar (Nattu Sarkarai).',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 4,
    tags: ['Organic', 'Brown Sugar', 'Tea']
  },
  {
    id: 'item-57',
    code: 'NS-COF',
    nameTamil: 'நாட்டுசர்க்கரை காபி',
    nameEnglish: 'Nattu Sarkarai Coffee (Country Brown Sugar Coffee)',
    category: 'Beverages / Hot Drinks',
    price: 17,
    isVeg: true,
    description: 'Rich filter coffee brewed with traditional organic brown sugar.',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 4,
    tags: ['Organic', 'Brown Sugar', 'Coffee']
  },

  // ================= 2. SNACKS & EVENING BITES (ஸ்நாக்ஸ்) =================
  {
    id: 'item-9',
    code: 'VAD-01',
    nameTamil: 'வடை',
    nameEnglish: 'Vada (Medu Vada)',
    category: 'Snacks & Evening Bites',
    price: 7,
    isVeg: true,
    description: 'Crispy golden fried lentil doughnut vada with onions, ginger and curry leaves.',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 2,
    tags: ['Crispy', 'Snack', 'Breakfast']
  },
  {
    id: 'item-10',
    code: 'PUF-V',
    nameTamil: 'வெஜ் பப்ஸ்',
    nameEnglish: 'Veg Puff',
    category: 'Snacks & Evening Bites',
    price: 15,
    isVeg: true,
    description: 'Flaky baked pastry stuffed with spicy potato and mixed vegetable masala.',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 2,
    tags: ['Bakery', 'Puff', 'Snack']
  },
  {
    id: 'item-11',
    code: 'PUF-E',
    nameTamil: 'எக் பப்ஸ்',
    nameEnglish: 'Egg Puff',
    category: 'Snacks & Evening Bites',
    price: 20,
    isVeg: false,
    description: 'Crispy baked puff pastry filled with spiced hard-boiled egg and onion masala.',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 2,
    tags: ['Bakery', 'Egg', 'Snack']
  },
  {
    id: 'item-12',
    code: 'PUF-C',
    nameTamil: 'சிக்கன் பப்ஸ்',
    nameEnglish: 'Chicken Puff',
    category: 'Snacks & Evening Bites',
    price: 20,
    isVeg: false,
    description: 'Golden puff pastry loaded with savory shredded chicken masala.',
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 2,
    tags: ['Chicken', 'Puff', 'Hot']
  },
  {
    id: 'item-13',
    code: 'ROL-C',
    nameTamil: 'சிக்கன் ரோல்',
    nameEnglish: 'Chicken Roll',
    category: 'Snacks & Evening Bites',
    price: 25,
    isVeg: false,
    description: 'Breaded crispy fried roll stuffed with juicy spiced chicken filling.',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 4,
    tags: ['Roll', 'Chicken', 'Snack']
  },
  {
    id: 'item-14',
    code: 'BOM-01',
    nameTamil: 'பிரட் ஆம்லேட்',
    nameEnglish: 'Bread Omelette',
    category: 'Snacks & Evening Bites',
    price: 40,
    isVeg: false,
    description: 'Double eggs whisked with green chillies & onions, toasted golden with bread slices.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 6,
    tags: ['Egg', 'Bread', 'Campus Favorite']
  },
  {
    id: 'item-15',
    code: 'CBOM-01',
    nameTamil: 'சிக்கன் பிரட் ஆம்லேட்',
    nameEnglish: 'Chicken Bread Omelette',
    category: 'Snacks & Evening Bites',
    price: 50,
    isVeg: false,
    description: 'Loaded bread omelette stuffed with seasoned minced chicken chunks and spicy pepper.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 8,
    tags: ['Chicken', 'Egg', 'Special']
  },
  {
    id: 'item-16',
    code: 'SDW-V',
    nameTamil: 'சாண்ட்வெஜ்',
    nameEnglish: 'Veg Sandwich',
    category: 'Snacks & Evening Bites',
    price: 30,
    isVeg: true,
    description: 'Toasted sandwich layered with sliced vegetables, green chutney and house spices.',
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 6,
    tags: ['Sandwich', 'Veg']
  },
  {
    id: 'item-17',
    code: 'SDW-C',
    nameTamil: 'சிக்கன் சாண்ட்வெஜ்',
    nameEnglish: 'Chicken Sandwich',
    category: 'Snacks & Evening Bites',
    price: 40,
    isVeg: false,
    description: 'Grilled sandwich with tender spiced chicken tikka pieces and mayonnaise.',
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 7,
    tags: ['Chicken', 'Sandwich']
  },
  {
    id: 'item-22',
    code: 'SOM-01',
    nameTamil: 'சோமாஸ்',
    nameEnglish: 'Somas (Sweet Pastry Samosa)',
    category: 'Snacks & Evening Bites',
    price: 10,
    isVeg: true,
    description: 'Crisp half-moon pastry filled with sweetened coconut and roasted gram stuffing.',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 2,
    tags: ['Sweet', 'Snack']
  },
  {
    id: 'item-23',
    code: 'BUN-01',
    nameTamil: 'பால் பன்',
    nameEnglish: 'Milk Bun (Bun Butter)',
    category: 'Snacks & Evening Bites',
    price: 10,
    isVeg: true,
    description: 'Soft sweet bakery milk bun, lightly buttered and sugar dusted.',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 1,
    tags: ['Bakery', 'Bun']
  },
  {
    id: 'item-44',
    code: 'OML-01',
    nameTamil: 'ஆம்லேட்',
    nameEnglish: 'Single Omelette',
    category: 'Snacks & Evening Bites',
    price: 15,
    isVeg: false,
    description: 'Fresh farm egg beaten with chopped onions, green chillies and crushed black pepper.',
    imageUrl: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 4,
    tags: ['Egg', 'Side']
  },
  {
    id: 'item-46',
    code: 'GOB-65',
    nameTamil: 'காளி பிளவர் 65',
    nameEnglish: 'Cauliflower 65 (Gobi 65)',
    category: 'Snacks & Evening Bites',
    price: 30,
    isVeg: true,
    description: 'Deep fried crispy marinated cauliflower florets seasoned with curry leaves and garlic.',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 6,
    tags: ['Gobi 65', 'Crispy', 'Spicy']
  },

  // ================= 3. CHAAT & STREET FOOD (சாட் வகைகள்) =================
  {
    id: 'item-18',
    code: 'PNP-01',
    nameTamil: 'பானிப்பூரி',
    nameEnglish: 'Pani Puri (Gol Gappe)',
    category: 'Chaat & Street Food',
    price: 20,
    isVeg: true,
    description: '6 crispy puris stuffed with potato-chickpea masala, filled with tangy mint-coriander pani.',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 4,
    tags: ['Chaat', 'Street Food', 'Popular']
  },
  {
    id: 'item-19',
    code: 'SWC-01',
    nameTamil: 'ஸ்வீட் கார்ன்',
    nameEnglish: 'Sweet Corn (Steamed Masala Corn)',
    category: 'Chaat & Street Food',
    price: 20,
    isVeg: true,
    description: 'Steamed tender sweet corn kernels tossed with pure butter, lime and chaat masala.',
    imageUrl: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 3,
    tags: ['Healthy', 'Chaat', 'Corn']
  },
  {
    id: 'item-20',
    code: 'MSP-01',
    nameTamil: 'மசால் பூரி',
    nameEnglish: 'Masala Puri',
    category: 'Chaat & Street Food',
    price: 20,
    isVeg: true,
    description: 'Crushed crisp puris drenched in hot spicy green pea gravy with onions and sev.',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 4,
    tags: ['Chaat', 'Spicy', 'Street Food']
  },
  {
    id: 'item-21',
    code: 'KLN-01',
    nameTamil: 'காளான்',
    nameEnglish: 'Kalan / Mushroom Fry (Roadside Style)',
    category: 'Chaat & Street Food',
    price: 30,
    isVeg: true,
    description: 'Famous Coimbatore style crispy fried mushroom & cabbage chunks tossed in rich spicy gravy.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 5,
    tags: ['Kalan', 'Mushroom', 'Signature']
  },

  // ================= 4. TIFFIN & BREAKFAST (டிபன் & காலை உணவு) =================
  {
    id: 'item-24',
    code: 'IDL-01',
    nameTamil: 'இட்லி',
    nameEnglish: 'Idli (Soft Steamed Rice Cake)',
    category: 'Tiffin & Breakfast',
    price: 7,
    isVeg: true,
    description: 'Fluffy steamed South Indian rice cake served with coconut chutney & piping hot sambar.',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 2,
    tags: ['Breakfast', 'Healthy', 'Tiffin']
  },
  {
    id: 'item-25',
    code: 'POR-01',
    nameTamil: 'பூரி செட்',
    nameEnglish: 'Poori Set (2 Puris with Potato Masala)',
    category: 'Tiffin & Breakfast',
    price: 30,
    isVeg: true,
    description: '2 puffy golden fried wheat pooris served with comforting spiced potato saagu/masala.',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 5,
    tags: ['Poori', 'Breakfast', 'Tiffin']
  },
  {
    id: 'item-26',
    code: 'PONG-01',
    nameTamil: 'பொங்கல்',
    nameEnglish: 'Ven Pongal (Ghee Pongal)',
    category: 'Tiffin & Breakfast',
    price: 40,
    isVeg: true,
    description: 'Creamy rice and yellow lentil dish tempered with pure ghee, whole black pepper, cumin and cashews.',
    imageUrl: 'https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 3,
    tags: ['Pongal', 'Ghee', 'South Indian']
  },
  {
    id: 'item-27',
    code: 'DOS-01',
    nameTamil: 'தோசை',
    nameEnglish: 'Crispy Plain Dosa',
    category: 'Tiffin & Breakfast',
    price: 30,
    isVeg: true,
    description: 'Golden crisp fermented crepe made of rice and lentils, served with 2 chutneys & sambar.',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 6,
    tags: ['Dosa', 'Tiffin', 'Crispy']
  },
  {
    id: 'item-28',
    code: 'UTH-01',
    nameTamil: 'ஊத்தப்பம்',
    nameEnglish: 'Uthappam',
    category: 'Tiffin & Breakfast',
    price: 20,
    isVeg: true,
    description: 'Thick, fluffy savory pancake cooked with golden crust and soft center.',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 6,
    tags: ['Uthappam', 'Tiffin']
  },

  // ================= 5. VARIETY RICE & MEALS (சாப்பாடு வகைகள்) =================
  {
    id: 'item-29',
    code: 'LMR-01',
    nameTamil: 'லெமன் சாதம்',
    nameEnglish: 'Lemon Rice (Elumichai Sadam)',
    category: 'Variety Rice & Meals',
    price: 40,
    isVeg: true,
    description: 'Zesty lemon flavoured rice tempered with mustard, roasted peanuts, curry leaves and green chillies.',
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 3,
    tags: ['Variety Rice', 'Lunch']
  },
  {
    id: 'item-30',
    code: 'TMR-01',
    nameTamil: 'தக்காளி சாதம்',
    nameEnglish: 'Tomato Rice (Thakkali Sadam)',
    category: 'Variety Rice & Meals',
    price: 40,
    isVeg: true,
    description: 'Fragrant rice cooked in rich spiced ripe tomato gravy with whole garam spices.',
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 3,
    tags: ['Variety Rice', 'Lunch']
  },
  {
    id: 'item-31',
    code: 'SBR-01',
    nameTamil: 'சாம்பார் சாதம்',
    nameEnglish: 'Sambar Rice (Bisibelebath style)',
    category: 'Variety Rice & Meals',
    price: 40,
    isVeg: true,
    description: 'Wholesome rice mashed with aromatic vegetable sambar and ghee.',
    imageUrl: 'https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 3,
    tags: ['Variety Rice', 'Sambar']
  },
  {
    id: 'item-32',
    code: 'CDR-01',
    nameTamil: 'தயிர் சாதம்',
    nameEnglish: 'Curd Rice (Thayir Sadam)',
    category: 'Variety Rice & Meals',
    price: 40,
    isVeg: true,
    description: 'Cooling seasoned fresh curd rice tempered with mustard, ginger, curry leaves & pomegranate.',
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 2,
    tags: ['Curd Rice', 'Cooling']
  },
  {
    id: 'item-35',
    code: 'MEAL-01',
    nameTamil: 'சாப்பாடு',
    nameEnglish: 'Full South Indian Meals (Sappadu)',
    category: 'Variety Rice & Meals',
    price: 80,
    isVeg: true,
    description: 'Unlimited steamed rice served with Sambar, Rasam, Kara Kuzhambu, Poriyal, Kootu, Appalam & Pickle.',
    imageUrl: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 5,
    tags: ['Full Meals', 'Thali', 'Lunch']
  },

  // ================= 6. BIRYANI & FAST FOOD (பிரியாணி & நூடுல்ஸ் & ரைஸ்) =================
  {
    id: 'item-33',
    code: 'BRY-V',
    nameTamil: 'வெஜ் பிரியாணி',
    nameEnglish: 'Veg Biryani',
    category: 'Biryani & Fast Food',
    price: 50,
    isVeg: true,
    description: 'Aromatic basmati rice cooked with fresh seasonal vegetables and authentic spices, served with raita.',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 5,
    tags: ['Biryani', 'Veg', 'Lunch']
  },
  {
    id: 'item-34',
    code: 'BRY-M',
    nameTamil: 'காளான் பிரியாணி',
    nameEnglish: 'Mushroom Biryani (Kalan Biryani)',
    category: 'Biryani & Fast Food',
    price: 60,
    isVeg: true,
    description: 'Flavourful seeraga samba rice dum-cooked with tender button mushrooms and mint masala.',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 5,
    tags: ['Mushroom', 'Biryani', 'Special']
  },
  {
    id: 'item-36',
    code: 'BRY-C',
    nameTamil: 'சிக்கன் பிரியாணி',
    nameEnglish: 'Chicken Biryani',
    category: 'Biryani & Fast Food',
    price: 100,
    isVeg: false,
    description: 'SRM special spiced dum chicken biryani served with boiled egg, brinjal gravy (dalcha) and onion raita.',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 5,
    tags: ['Chicken Biryani', 'Non-Veg', 'Bestseller']
  },
  {
    id: 'item-37',
    code: 'FR-V',
    nameTamil: 'வெஜ்ரைஸ்',
    nameEnglish: 'Veg Fried Rice',
    category: 'Biryani & Fast Food',
    price: 70,
    isVeg: true,
    description: 'Wok-tossed rice with shredded cabbage, carrots, bell peppers and scallions with light soy sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 7,
    tags: ['Fried Rice', 'Chinese']
  },
  {
    id: 'item-38',
    code: 'FR-E',
    nameTamil: 'எக்ரைஸ்',
    nameEnglish: 'Egg Fried Rice',
    category: 'Biryani & Fast Food',
    price: 70,
    isVeg: false,
    description: 'Wok-tossed rice scrambled with farm eggs, crunchy vegetables and crushed black pepper.',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 7,
    tags: ['Egg Rice', 'Chinese']
  },
  {
    id: 'item-39',
    code: 'FR-C',
    nameTamil: 'சிக்கன் ரைஸ்',
    nameEnglish: 'Chicken Fried Rice',
    category: 'Biryani & Fast Food',
    price: 80,
    isVeg: false,
    description: 'Aromatic wok-fried rice tossed with spiced tender chicken morsels, egg and spring onions.',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 8,
    tags: ['Chicken', 'Fried Rice', 'Popular']
  },
  {
    id: 'item-40',
    code: 'NOD-C',
    nameTamil: 'சிக்கன் நூடுல்ஸ்',
    nameEnglish: 'Chicken Noodles',
    category: 'Biryani & Fast Food',
    price: 70,
    isVeg: false,
    description: 'Stir-fried noodles with shredded chicken chunks, egg ribbons and crunchy julienned veggies.',
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 8,
    tags: ['Noodles', 'Chicken']
  },
  {
    id: 'item-41',
    code: 'NOD-E',
    nameTamil: 'எக் நூடுல்ஸ்',
    nameEnglish: 'Egg Noodles',
    category: 'Biryani & Fast Food',
    price: 70,
    isVeg: false,
    description: 'Hot wok-tossed Hakka noodles tossed with scrambled eggs and garden vegetables.',
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 7,
    tags: ['Noodles', 'Egg']
  },

  // ================= 7. PAROTTA & SIDES (புரோட்டா வகைகள்) =================
  {
    id: 'item-42',
    code: 'PAR-CHL',
    nameTamil: 'சில்லி புரோட்டா',
    nameEnglish: 'Chilli Parotta',
    category: 'Parotta & Sides',
    price: 70,
    isVeg: true,
    description: 'Shredded crispy layered parotta tossed in spicy Chinese wok with capsicum, onion and chilli paste.',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 8,
    tags: ['Parotta', 'Spicy', 'Fast Food']
  },
  {
    id: 'item-43',
    code: 'PAR-01',
    nameTamil: 'புரோட்டா',
    nameEnglish: 'Single Parotta (Malabar Layered Parotta)',
    category: 'Parotta & Sides',
    price: 15,
    isVeg: true,
    description: 'Hot, flaky, multi-layered tawa parotta beaten soft, served with rich vegetable salna.',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 3,
    tags: ['Parotta', 'Salna']
  },
  {
    id: 'item-45',
    code: 'PAR-MUT',
    nameTamil: 'முட்டை புரோட்டா',
    nameEnglish: 'Muttai Parotta (Egg Kothu Parotta)',
    category: 'Parotta & Sides',
    price: 80,
    isVeg: false,
    description: 'Famous Madurai style minced layered parotta cooked with eggs, chicken salna, onions and curry leaves.',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 9,
    tags: ['Kothu Parotta', 'Egg', 'Bestseller']
  },

  // ================= 8. FRESH JUICE & COOLERS (ஜூஸ் & குளிர்பானங்கள்) =================
  {
    id: 'item-47',
    code: 'JUC-LEM',
    nameTamil: 'லெமன் சர்பத்',
    nameEnglish: 'Lemon Sarbath',
    category: 'Fresh Juices & Coolers',
    price: 20,
    isVeg: true,
    description: 'Refreshing chilled sweet lemon cooler with nannari syrup essence.',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 3,
    tags: ['Juice', 'Cooler', 'Summer']
  },
  {
    id: 'item-48',
    code: 'JUC-WAT',
    nameTamil: 'வாட்டர் மிலன் ஜூஸ்',
    nameEnglish: 'Watermelon Juice',
    category: 'Fresh Juices & Coolers',
    price: 30,
    isVeg: true,
    description: '100% fresh cold-pressed crisp watermelon juice served chilled.',
    imageUrl: 'https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 4,
    tags: ['Fresh Juice', 'Hydrating']
  },
  {
    id: 'item-49',
    code: 'JUC-MSB',
    nameTamil: 'சாத்துக்குடி ஜூஸ்',
    nameEnglish: 'Mosambi Juice (Sweet Lime)',
    category: 'Fresh Juices & Coolers',
    price: 50,
    isVeg: true,
    description: 'Freshly extracted sweet lime juice rich in Vitamin C.',
    imageUrl: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 5,
    tags: ['Fresh Juice', 'Vitamin C']
  },
  {
    id: 'item-50',
    code: 'JUC-MSK',
    nameTamil: 'முலாம்பழம் ஜூஸ்',
    nameEnglish: 'Muskmelon Juice (Kirni Fruit)',
    category: 'Fresh Juices & Coolers',
    price: 50,
    isVeg: true,
    description: 'Creamy and sweet musk melon puree drink served on crushed ice.',
    imageUrl: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: false,
    preparationTimeMinutes: 5,
    tags: ['Fresh Juice', 'Cooling']
  },
  {
    id: 'item-51',
    code: 'JUC-MOJ',
    nameTamil: 'மொஜிட்டோ',
    nameEnglish: 'Virgin Mint Mojito',
    category: 'Fresh Juices & Coolers',
    price: 40,
    isVeg: true,
    description: 'Sparkling cooler with muddled fresh mint leaves, lime juice and soda.',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    isSpecial: true,
    preparationTimeMinutes: 4,
    tags: ['Mojito', 'Sparkling', 'Trending']
  }
];

export const INITIAL_SETTINGS: CanteenSettings = {
  isCanteenOpen: true,
  bannerNotice: '⚡ SRM KDFC Digital Ordering active! Collect your token at Counter 1 & 2.',
  workingHours: '7:30 AM - 7:30 PM (Mon-Sat)',
  location: 'KDFC Food Court, Ground Floor, SRM MCET Campus',
  contactPhone: '+91 94430 00000 (Counter Inquiry)',
  contactEmail: 'kdfc.canteen@srmmcet.edu.in',
  upiId: 'srmkdfc@sbi',
  defaultPrepTimeMinutes: 10,
  allowAdvanceOrders: true
};
